services:
  strapi:
    container_name: lms_backend
    build:
      context: ./backend
      dockerfile: ../Dockerfile.strapi
    image: strapi_app:latest
    restart: always
    env_file: .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_SSL: ${DATABASE_SSL}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      APP_KEYS: ${APP_KEYS}
      API_TOKEN_SALT: ${API_TOKEN_SALT}
      TRANSFER_TOKEN_SALT: ${TRANSFER_TOKEN_SALT}
    ports:
      - "1337:1337"
      - "5173:5173"
    volumes:
      - ./backend:/opt/app
      - ./backend/.tmp:/opt/app/.tmp

  frontend:
    container_name: lms_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    image: react_frontend:latest
    restart: always
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/opt/app
      - /opt/app/node_modules
    depends_on:
      - db
      - strapi

  db:
    container_name: lms_db
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 256M
    command: >
      postgres
      -c 'shared_buffers=64MB'
      -c 'max_connections=20'
      -c 'work_mem=4MB'

volumes:
  postgres_data:
