FROM node:20-alpine

RUN apk update && apk add --no-cache build-base gcc autoconf automake zlib-dev libpng-dev vips-dev > /dev/null 2>&1

ENV NODE_ENV=development
ENV NODE_OPTIONS=--max-old-space-size=1024

WORKDIR /opt/
COPY package.json package-lock.json* ./
RUN npm install && npm cache clean --force
ENV PATH /opt/node_modules/.bin:$PATH

WORKDIR /opt/app
COPY . .
RUN NODE_OPTIONS="--max-old-space-size=1024" npm run build
EXPOSE 1337
CMD ["npm", "run", "develop"]