FROM node:20-alpine

RUN apk update && apk add --no-cache build-base gcc autoconf automake zlib-dev libpng-dev vips-dev > /dev/null 2>&1

ENV NODE_ENV=production
ENV NODE_OPTIONS=--max-old-space-size=1024

WORKDIR /opt/
COPY package.json package-lock.json* ./
RUN npm install && npm cache clean --force
ENV PATH /opt/node_modules/.bin:$PATH

WORKDIR /opt/app
COPY . .
# Ya no hace npm run build, copia el .tmp/dist generado en el host
EXPOSE 1337
CMD ["npm", "run", "start"]